name: release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      snapshot:
        description: Force a dev version to be generated, implies dry_run.
        type: boolean
        required: true
      dry_run:
        description: Perform a dry-run release.
        type: boolean
        required: true

permissions:
  # Required to publish a release
  contents: write
  # Necessary to push docker images to ghcr.io.
  packages: write

env:
  WGTUNNEL_RELEASE: ${{ github.event.inputs.snapshot && 'false' || 'true' }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      # If the event that triggered the build was an annotated tag (which our
      # tags are supposed to be), actions/checkout has a bug where the tag in
      # question is only a lightweight tag and not a full annotated tag. This
      # command seems to fix it.
      # https://github.com/actions/checkout/issues/290
      - name: Fetch git tags
        run: git fetch --tags --force

      - name: Docker Login
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: "~1.22"
          cache: false

      - name: Build tunneld and Docker images
        id: build
        run: |
          set -euo pipefail
          go mod download

          make clean
          make -j build/tunneld build/tunneld.tag

          image_tag=$(cat build/tunneld.tag)
          if [[ "$image_tag" == "" ]]; then
            echo "No tag found in build/tunneld.tag"
            exit 1
          fi

          echo "docker_tag=${image_tag}" >> "$GITHUB_OUTPUT"

      - name: Push Docker image
        if: ${{ !github.event.inputs.dry_run && !github.event.inputs.snapshot }}
        env:
          DOCKER_TAG: ${{ steps.build.outputs.docker_tag }}
        run: |
          set -euxo pipefail

          image_tag="$DOCKER_TAG"
          docker push "$image_tag"

          latest_tag="ghcr.io/coder/wgtunnel/tunneld:latest"
          docker tag "$image_tag" "$latest_tag"
          docker push "$latest_tag"

      - name: ls build
        run: ls -lh build

      - name: Publish release
        if: ${{ !github.event.inputs.dry_run && !github.event.inputs.snapshot }}
        uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
        with:
          artifacts: "build/tunneld"
          body: "Docker image: `${{ steps.build.outputs.docker_tag }}`"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts to actions (if dry-run or snapshot)
        if: ${{ github.event.inputs.dry_run || github.event.inputs.snapshot }}
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: release-artifacts
          path: |
            ./build/tunneld
          retention-days: 7
